# Generated by Django 3.1.6 on 2021-04-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210405_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approve'), (3, 'Reject')], default=1),
        ),
    ]
