# Generated by Django 3.1.6 on 2021-04-05 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_request_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='users.userprofile'),
        ),
    ]
