# Generated by Django 3.1.6 on 2021-03-06 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210306_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=255, null=True)),
                ('role', models.PositiveSmallIntegerField(default=1, verbose_name=((1, 'Customer'), (2, 'Seller'), (3, 'Admin')))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
