# Generated by Django 3.1.6 on 2021-03-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210306_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
