# Generated by Django 3.1.6 on 2021-03-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210314_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_seller',
        ),
    ]
