# Generated by Django 3.1.6 on 2021-02-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(max_length=255)),
                ('short_description', models.TextField()),
                ('price', models.FloatField()),
                ('list_price', models.FloatField()),
                ('price_usd', models.FloatField()),
                ('discount', models.FloatField()),
                ('discount_rate', models.FloatField()),
                ('rating_average', models.FloatField()),
                ('product_group_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
