# Generated by Django 3.1.6 on 2021-03-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='status',
            field=models.CharField(choices=[(1, 'Active'), (2, 'Deactivate'), (3, 'Finish')], default=1, max_length=2),
        ),
    ]
