# Generated by Django 3.1.6 on 2021-04-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='lowest_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
