# Generated by Django 3.1.6 on 2021-02-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Production',
            new_name='Product',
        ),
    ]
