# Generated by Django 3.1.6 on 2021-06-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0003_auto_20210405_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='status',
            field=models.CharField(choices=[(1, 'Active'), (2, 'Deactivate'), (3, 'Delete')], default=1, max_length=2),
        ),
    ]
