# Generated by Django 3.1.6 on 2021-02-19 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0004_auto_20210219_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='watches.product'),
        ),
    ]
