# Generated by Django 3.1.6 on 2021-02-21 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0005_auto_20210219_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='product_id',
            new_name='product',
        ),
    ]
