# Generated by Django 3.1.6 on 2021-02-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0006_auto_20210221_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='product',
            new_name='product_id',
        ),
    ]
