# Generated by Django 3.1.6 on 2021-02-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0007_auto_20210221_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='product_id',
            new_name='product',
        ),
    ]
