# Generated by Django 3.1.6 on 2021-02-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0010_auto_20210225_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
