# Generated by Django 3.1.6 on 2021-02-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0011_auto_20210225_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_usd',
        ),
    ]
