# Generated by Django 3.1.6 on 2021-02-27 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watches', '0012_remove_product_price_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='auth.user'),
            preserve_default=False,
        ),
    ]
