# Generated by Django 3.1.6 on 2021-03-10 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('watches', '0015_auto_20210310_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='product',
            field=models.ForeignKey(default=7048315, on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='products.product'),
            preserve_default=False,
        ),
    ]
