# Generated by Django 3.1.6 on 2021-03-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(max_length=255)),
                ('short_description', models.TextField()),
                ('price', models.FloatField()),
                ('list_price', models.FloatField()),
                ('discount', models.FloatField()),
                ('discount_rate', models.FloatField()),
                ('rating_average', models.FloatField()),
                ('product_group_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.seller')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
