# Generated by Django 3.1.6 on 2021-06-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='is_best_store',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
